"""fnmusic-ext 管理 WebUI（fnmusic-sources 容器内第四个 supervisor 进程）。

定位：同容器内经 127.0.0.1 访问三源服务，subprocess 调 supervisorctl 切换音源
进程，直接读写挂载在 /repo 的仓库目录下的 .env（proxy 靠热重载生效）。
不挂 docker.sock、不做容器级操作。管理接口只接受飞牛网关注入的管理员身份。

前端为原生单页（static/，无构建、无 CDN 资产）。
"""
from __future__ import annotations

import asyncio
import io
import logging
import os
import re
import subprocess
import sys
import time
from contextlib import asynccontextmanager
from pathlib import Path

import httpx
from fastapi import FastAPI, HTTPException, Query, Request
from fastapi.responses import FileResponse, JSONResponse, Response
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))  # /repo：复用 proxy/env_merge
sys.path.insert(0, str(Path(__file__).resolve().parent))       # 本目录：upgrade 模块
from proxy.env_merge import (  # noqa: E402
    parse_env_file,
    preserve_user_comments,
    render_env,
    write_env_atomic,
)
import upgrade  # noqa: E402

logger = logging.getLogger("webui_service")
logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(name)s: %(message)s")

SERVICE_VERSION = "2.0.0"

CONF = {
    "repo_dir": os.environ.get("WEBUI_REPO_DIR", "/repo"),
    "musicdl_url": os.environ.get("WEBUI_MUSICDL_URL", "http://127.0.0.1:8001"),
    "musicbox_url": os.environ.get("WEBUI_MUSICBOX_URL", "http://127.0.0.1:8002"),
    "lx_url": os.environ.get("WEBUI_LX_URL", "http://127.0.0.1:8003"),
    "supervisorctl": os.environ.get("WEBUI_SUPERVISORCTL", "supervisorctl"),
    "env_header": "generated by install.sh — do not commit",
}

ENV_PATH = Path(CONF["repo_dir"]) / ".env"
VERSION_PATH = Path(CONF["repo_dir"]) / "VERSION"
STATIC_DIR = Path(__file__).resolve().parent / "static"

# 音源进程 ↔ 启用开关（三选一互斥）
PROVIDERS = {
    "musicdl": "FNMUSIC_MUSICDL_ENABLED",
    "musicbox": "FNMUSIC_NETEASE_ENABLED",
    "lxmusic": "FNMUSIC_LX_ENABLED",
}

# WebUI 可管理的配置键与元数据（kind/default/reload 驱动前端渲染与校验）。
# reload: hot=proxy 热重载即生效；process=需要切换/重启对应音源进程。
SCHEMA: dict[str, dict] = {
    "FNMUSIC_MUSICDL_ENABLED": {"kind": "bool", "default": "false", "group": "provider", "reload": "process", "label": "musicdl 聚合音源"},
    "FNMUSIC_NETEASE_ENABLED": {"kind": "bool", "default": "false", "group": "provider", "reload": "process", "label": "网易云音乐盒子"},
    "FNMUSIC_LX_ENABLED": {"kind": "bool", "default": "false", "group": "provider", "reload": "process", "label": "洛雪自定义源"},
    "FNMUSIC_ONLINE_SOURCES": {"kind": "csv", "default": "", "group": "musicdl", "reload": "process", "label": "musicdl 启用平台"},
    "MUSICDL_SOURCES": {"kind": "csv", "default": "", "group": "musicdl", "reload": "process", "label": "musicdl 服务白名单（联动）"},
    "LX_SOURCE_URL": {"kind": "str", "default": "", "group": "lx", "reload": "process", "label": "洛雪源脚本地址（http(s) URL 或 file:// 上传地址）"},
    "LX_SOURCES": {"kind": "csv", "default": "kg,wy,mg,kw", "group": "lx", "reload": "hot", "label": "lx 平台（按源声明推导）"},
    "FNMUSIC_QUALITY_MODE": {"kind": "enum", "values": ["high", "balanced", "smooth"], "default": "high", "group": "quality", "reload": "hot", "label": "音质偏好"},
    "FNMUSIC_RECOMMEND_HOT": {"kind": "bool", "default": "true", "group": "recommend", "reload": "hot", "label": "热门榜单推荐"},
    "FNMUSIC_RECOMMEND_DAILY": {"kind": "bool", "default": "true", "group": "recommend", "reload": "hot", "label": "每日推荐"},
    "FNMUSIC_TEE_SAVE_ENABLED": {"kind": "bool", "default": "true", "group": "tee", "reload": "hot", "label": "边听边存"},
    "FNMUSIC_TEE_SAVE_DIR": {"kind": "str", "default": "", "group": "tee", "reload": "hot", "label": "保存路径（留空自动探测）"},
    "FNMUSIC_TEE_CACHE_MAX": {"kind": "int", "default": "2", "min": 1, "max": 100, "group": "tee", "reload": "hot", "label": "关闭时滚动缓存数"},
    "FNMUSIC_FAV_AUTO_BIND": {"kind": "bool", "default": "false", "group": "tee", "reload": "hot", "label": "收藏自动绑定本地"},
    "FNMUSIC_AUTO_COVER": {"kind": "bool", "default": "true", "group": "tee", "reload": "hot", "label": "自动下载封面"},
    "FNMUSIC_LYRIC_AUTO_DL": {"kind": "bool", "default": "false", "group": "tee", "reload": "hot", "label": "自动下载歌词"},
    "FNMUSIC_OFFICIAL_BIND_TIMEOUT_S": {"kind": "int", "default": "120", "min": 10, "max": 3600, "group": "tee", "reload": "hot", "label": "官方绑定等待（秒）"},
    "FNMUSIC_TEE_HANDOFF_MAX": {"kind": "int", "default": "3", "min": 0, "max": 20, "group": "tee", "reload": "hot", "label": "切歌续传并行数"},
    "FNMUSIC_LIBRARY_SCAN_PATH": {"kind": "str", "default": "", "group": "tee", "reload": "hot", "label": "曲库重扫接口（选填）"},
    "FNMUSIC_LLM_BASE_URL": {"kind": "str", "default": "", "group": "llm", "reload": "hot", "label": "OpenAI 兼容 Base URL"},
    "FNMUSIC_LLM_API_KEY": {"kind": "secret", "default": "", "group": "llm", "reload": "hot", "label": "API Key"},
    "FNMUSIC_LLM_MODEL": {"kind": "str", "default": "gpt-4o-mini", "group": "llm", "reload": "hot", "label": "模型"},
    "FNMUSIC_SEARCH_TIMEOUT": {"kind": "int", "default": "15", "min": 1, "max": 60, "group": "search", "reload": "hot", "label": "搜索超时时间"},
    "FNMUSIC_SEARCH_PROBE": {"kind": "bool", "default": "false", "group": "search", "reload": "hot", "label": "逐曲探活(beta)"},
    "FNMUSIC_NETEASE_MY_PLAYLISTS": {"kind": "bool", "default": "false", "group": "source", "reload": "hot", "label": "网易账号歌单"},
}

_PROVIDER_KEYS = set(PROVIDERS.values())


# ------------------------------------------------------------------ .env 读写 --

def read_env() -> dict[str, str]:
    kv, _ = parse_env_file(ENV_PATH)
    return dict(kv)


def current_provider(values: dict[str, str]) -> str:
    for name, key in PROVIDERS.items():
        if values.get(key, "false").lower() in ("true", "1", "yes"):
            return name
    return ""


def write_env(updates: dict[str, str]) -> list[str]:
    """把 updates 合并进 .env（显式覆盖），原子写 + 备份 + 保留用户自定义键与注释。

    返回实际发生变化的键列表。
    """
    existing_kv, others = parse_env_file(ENV_PATH)
    existing_map = dict(existing_kv)
    changed: list[str] = []
    for key, value in updates.items():
        if existing_map.get(key) != value:
            changed.append(key)
    if not changed:
        return []
    if ENV_PATH.exists():
        # with_suffix 会把 ".env" 当后缀替换，产出 ".env.env.webui.bak" 畸形名；拼名字才是 /repo/.env.webui.bak
        backup = ENV_PATH.with_name(ENV_PATH.name + ".webui.bak")
        try:
            backup.write_bytes(ENV_PATH.read_bytes())
            os.chmod(backup, 0o600)  # write_bytes 按 umask 落盘（0644），密钥备份必须收紧
        except OSError as exc:  # 备份失败不阻断写入，但要有迹可循
            logger.warning("webui env backup failed: %s", exc)
    merged = [(k, updates.get(k, v)) if k in updates else (k, v) for k, v in existing_kv]
    seen = {k for k, _ in merged}
    merged.extend((k, v) for k, v in updates.items() if k not in seen)
    write_env_atomic(
        ENV_PATH,
        render_env(
            merged,
            CONF["env_header"],
            trailing=preserve_user_comments(others, header=CONF["env_header"]),
        ),
    )
    return changed


# ------------------------------------------------------------------ supervisor --

def supervisorctl(*args: str, timeout: float = 20.0) -> tuple[int, str]:
    cmd = [CONF["supervisorctl"], *args]
    try:
        proc = subprocess.run(cmd, capture_output=True, text=True, timeout=timeout)
    except FileNotFoundError:
        return 127, "supervisorctl not found"
    except subprocess.TimeoutExpired:
        return 124, f"supervisorctl {' '.join(args)} timed out"
    output = (proc.stdout or "") + (proc.stderr or "")
    return proc.returncode, output.strip()


def supervisor_status() -> dict[str, dict]:
    # supervisorctl status 的退出码语义是“是否全部 RUNNING”（存在 STOPPED 即 3、
    # 存在 FATAL 即 4），按需加载架构下未选中的音源常驻 STOPPED 是正常态，
    # 不能用退出码判成败：只认输出里能解析出的状态行；连接失败等异常输出
    # 解析不出任何状态行，自然返回空表（前端显示未知）。
    _, out = supervisorctl("status")
    result: dict[str, dict] = {}
    for line in out.splitlines():
        parts = line.split()
        if len(parts) >= 2 and parts[1] in ("RUNNING", "STOPPED", "STARTING", "FATAL", "BACKOFF", "EXITED"):
            result[parts[0]] = {"state": parts[1], "detail": " ".join(parts[2:])}
    return result


def switch_provider_process(old: str, new: str) -> list[dict]:
    """切源进程：先停旧再起新；失败逐项记录，不抛出。"""
    actions: list[dict] = []
    if old and old != new:
        code, out = supervisorctl("stop", old)
        actions.append({"kind": "process", "program": old, "op": "stop",
                        "ok": code == 0, "error": "" if code == 0 else out})
    if new:
        code, out = supervisorctl("start", new)
        actions.append({"kind": "process", "program": new, "op": "start",
                        "ok": code == 0, "error": "" if code == 0 else out})
    return actions


# ------------------------------------------------------------------ 音源预览（临时拉起） --
# WebUI 点选未启用的音源卡片时临时拉起对应进程（仅 supervisorctl，不写 .env），
# 让 lx 测试 / musicdl 平台列表 / 网易扫码立即可用：
# - 保存后转正（正式启用）或被立即清退（api_config 保存路径 reconcile）；
# - 只点选未保存的，PREVIEW_TTL 秒无访问后自动停止（选平台/测试源/扫码会续期）。
PREVIEW_TTL = 300.0
_preview_until: dict[str, float] = {}

PROVIDER_PROGRAM = {"musicdl": "musicdl", "musicbox": "musicbox", "lxmusic": "lxmusic"}
PROVIDER_HEALTH = {"musicdl": CONF["musicdl_url"], "musicbox": CONF["musicbox_url"], "lxmusic": CONF["lx_url"]}


def preview_seconds_left(provider: str) -> float:
    deadline = _preview_until.get(provider)
    return max(0.0, deadline - time.monotonic()) if deadline else 0.0


def preview_renew(provider: str) -> None:
    if provider in _preview_until:
        _preview_until[provider] = time.monotonic() + PREVIEW_TTL


def preview_reap() -> list[str]:
    """清退到期预览：已随保存启用的转正（移出预览表，进程常驻），其余停止。

    stop 失败（supervisorctl 抖动/超时）不 pop 表项：deadline 仍过期，
    下一轮 reaper 会重试——否则预览进程漏停后常驻，无人再管。
    """
    stopped: list[str] = []
    enabled = current_provider(read_env())
    for provider, deadline in list(_preview_until.items()):
        if provider == enabled:
            _preview_until.pop(provider, None)
        elif deadline <= time.monotonic():
            code, out = supervisorctl("stop", PROVIDER_PROGRAM[provider])
            if code == 0:
                _preview_until.pop(provider, None)
                logger.info("预览到期，停止音源进程 %s", provider)
                stopped.append(provider)
            else:
                logger.warning("预览到期但停止失败（下轮重试）%s: %s", provider, out)
    return stopped


def preview_reconcile_after_save() -> list[dict]:
    """保存成功后的收尾：预览转正的进程保留，其余预览进程立即停止。"""
    enabled = current_provider(read_env())
    actions: list[dict] = []
    for provider in list(_preview_until):
        if provider == enabled:
            _preview_until.pop(provider, None)
            continue
        _preview_until.pop(provider, None)
        code, out = supervisorctl("stop", PROVIDER_PROGRAM[provider])
        actions.append({"kind": "process", "program": PROVIDER_PROGRAM[provider], "op": "stop",
                        "ok": code == 0, "error": "" if code == 0 else out, "preview": True})
    return actions


# ------------------------------------------------------------------ 校验 --

def _normalize_value(key: str, raw) -> str:
    spec = SCHEMA[key]
    kind = spec["kind"]
    if kind == "bool":
        if isinstance(raw, bool):
            return "true" if raw else "false"
        text = str(raw).strip().lower()
        if text in ("true", "1", "yes", "on"):
            return "true"
        if text in ("false", "0", "no", "off", ""):
            return "false"
        raise ValueError(f"{key}: 期望 true/false，收到 {raw!r}")
    if kind == "int":
        try:
            num = int(str(raw).strip())
        except ValueError as exc:
            raise ValueError(f"{key}: 期望整数，收到 {raw!r}") from exc
        num = max(int(spec.get("min", num)), min(int(spec.get("max", num)), num))
        return str(num)
    if kind == "enum":
        text = str(raw).strip()
        if text not in spec["values"]:
            raise ValueError(f"{key}: 可选值 {'/'.join(spec['values'])}，收到 {raw!r}")
        return text
    if kind == "csv":
        items: list[str] = []
        if isinstance(raw, list):
            raw_list = [str(x) for x in raw]
        else:
            raw_list = [x for x in str(raw).replace("，", ",").split(",")]
        for item in raw_list:
            item = item.strip()
            if item and item not in items:
                items.append(item)
        return ",".join(items)
    return str(raw).strip()


def validate_updates(values: dict) -> dict[str, str]:
    updates: dict[str, str] = {}
    for key, raw in (values or {}).items():
        if key not in SCHEMA:
            raise ValueError(f"不支持的配置键: {key}")
        updates[key] = _normalize_value(key, raw)
    # 三选一互斥：以"应用后的最终状态"判断
    final = dict(read_env())
    final.update(updates)
    enabled = [name for name, key in PROVIDERS.items()
               if final.get(key, SCHEMA[key]["default"]).lower() in ("true", "1", "yes")]
    if len(enabled) > 1:
        raise ValueError(f"音源三选一：{'、'.join(enabled)} 同时启用，请只保留一个")
    if updates.keys() & _PROVIDER_KEYS and not enabled:
        raise ValueError("至少需要启用一个音源")
    return updates


# ------------------------------------------------------------------ HTTP 客户端 --

from contextlib import asynccontextmanager


@asynccontextmanager
async def _lifespan(_app: FastAPI):
    async def _preview_reaper():
        while True:
            await asyncio.sleep(15.0)
            try:
                preview_reap()
            except Exception:  # noqa: BLE001
                logger.exception("预览清退循环异常")
    reaper = asyncio.create_task(_preview_reaper())
    # 清掉上次升级残留的临时安装包（离线包 400MB+，不清会白占磁盘）
    try:
        upgrade.cleanup()
    except Exception:  # noqa: BLE001
        logger.exception("升级临时目录清理失败")
    try:
        yield
    finally:
        reaper.cancel()
        client = getattr(_app.state, "http", None)
        if client is not None:
            await client.aclose()
            _app.state.http = None


app = FastAPI(title="fnmusic-webui", version=SERVICE_VERSION, lifespan=_lifespan)


def get_http(request: Request) -> httpx.AsyncClient:
    client = getattr(request.app.state, "http", None)
    if client is None:
        client = httpx.AsyncClient(timeout=httpx.Timeout(8.0, connect=3.0))
        request.app.state.http = client
    return client


def _resp_json(resp: httpx.Response) -> dict:
    """防御性解析同容器服务的响应体：上游裸 500 等非 JSON 文本时返回带 error 的
    字典而不是抛 JSONDecodeError（否则自身也会 500，用户只能看到 "HTTP 500"）。"""
    try:
        return resp.json() if resp.content else {}
    except Exception:  # noqa: BLE001
        return {"ok": False, "error": f"上游返回非 JSON 响应（HTTP {resp.status_code}）"}


async def _fetch_json(request: Request, url: str, *, timeout: float = 4.0) -> "tuple[bool, dict]":
    client = get_http(request)
    try:
        resp = await client.get(url, timeout=timeout)
        data = _resp_json(resp)
        return resp.status_code < 400 and data.get("ok", True), data
    except Exception as exc:  # noqa: BLE001
        return False, {"error": str(exc)}


def _read_version() -> str:
    try:
        return VERSION_PATH.read_text(encoding="utf-8").strip()
    except OSError:
        return SERVICE_VERSION


# ------------------------------------------------------------------ 版本检测 --
#
# 定位：**只做「提示 + 跳转」，不做强制升级，也不代为安装**。
# 用户可完全无视新版本提示继续使用当前版本；任何检测失败都必须静默降级，
# 绝不影响管理台其余功能（拉不到远端就当作「未检查」，不报错、不阻塞）。
#
# 检测走 GitHub / Gitee 双通道：国内 NAS 直连 GitHub 常被墙，Gitee 作为镜像
# 兜底，任一通道成功即返回；两个都失败则降级为 checked=False。
#
# ⚠️ 两个关键约束（都踩过）：
#  1. 仓库必须是 REPO_OWNER/REPO_NAME 指向的自建 fork，不能用上游 javycoder ——
#     上游只发到 2.6.3，用错仓库会让检测永远停在旧版却显示"已是最新"。
#  2. 不盲信 releases/latest：它是"被标记为 latest 的版本"，不保证版本号最大
#     （预发布/草稿会被排除，latest 标记也可能指向旧版）。故同时拉 releases 列表，
#     取其中版本号最大的那条为准，避免版本号倒退的误判。

CHANGELOG_PATH = Path(CONF["repo_dir"]) / "CHANGELOG.md"

# 仓库坐标：本项目 fork 自 javycoder/fnos_music_ext，上游只发到 2.6.3；
# 2.6.16 及之后的发行版发布在 haonanren118/fnos_music_ext（自建发行页）。
# 指向错仓库会让版本检测永远停在旧版（表现为"已是最新"的假象）。
REPO_OWNER = "haonanren118"
REPO_NAME = "fnos_music_ext"

RELEASE_SOURCES = (
    {
        "name": "GitHub",
        "api": f"https://api.github.com/repos/{REPO_OWNER}/{REPO_NAME}/releases/latest",
        "list_api": f"https://api.github.com/repos/{REPO_OWNER}/{REPO_NAME}/releases?per_page=10",
        "page": f"https://github.com/{REPO_OWNER}/{REPO_NAME}/releases",
        # GitHub 未认证 API 只有 60 次/小时/IP（实测被限流后整源不可用）。
        # 配一个只读 PAT（token=True，见 _github_token）即可提到 5000 次/小时。
        "token": True,
        "headers": {
            "Accept": "application/vnd.github+json",
        },
    },
    {
        # Gitee 镜像账号与 GitHub 不同：GitHub 是 haonanren118，Gitee 是 yygitee118。
        # 曾误用 GitHub 用户名拼 Gitee 地址 → gitee.com/haonanren118/... 整站 404
        # （该账号在 Gitee 上根本不存在），用户点击镜像链接直接落到死链。
        # 现两侧各用各的账号，且展示前会探测可达性，不可达的一律不展示。
        "name": "Gitee",
        "api": "https://gitee.com/api/v5/repos/yygitee118/fnos_music_ext/releases/latest",
        "list_api": "https://gitee.com/api/v5/repos/yygitee118/fnos_music_ext/releases?per_page=10",
        "page": "https://gitee.com/yygitee118/fnos_music_ext/releases",
        "headers": {},
    },
)

_VERSION_RE = re.compile(r"^v?(\d+)\.(\d+)\.(\d+)")

# GitHub 只读令牌（fine-grained PAT，Contents:Read-only）。作用仅是把匿名 API 的
# 60 次/小时提到 5000 次/小时，不写仓库、不上传、不参与版本检测以外任何请求。
#
# 为什么支持"从文件读"而不只用环境变量：容器由应用中心统一拉起，网关/systemd 单元
# 里塞环境变量既难改又会随 fpk 复制到处走；而令牌文件放在 sources-data/config/ 下，
# 打包脚本已 `--exclude='sources-data/'`，绝不会混进发行包。
#
# 优先级：环境变量 GITHUB_TOKEN > 令牌文件（容器内 /data/config，宿主仓库同名目录）。
# 两者都取不到就是匿名访问，功能不会坏，只是可能因限流退化为只读 Gitee 镜像。
_GITHUB_TOKEN_FILES = (
    "/data/config/github_token.txt",
    str(Path(CONF["repo_dir"]) / "sources-data" / "config" / "github_token.txt"),
)


def _github_token() -> str:
    """取 GitHub 只读令牌；没有则返回空串（走匿名访问，功能不降级）。"""
    tok = (os.environ.get("GITHUB_TOKEN") or "").strip()
    if tok:
        return tok
    for raw in _GITHUB_TOKEN_FILES:
        try:
            tok = Path(raw).read_text(encoding="utf-8").strip()
        except OSError:
            continue
        if tok:
            return tok
    return ""


def _source_headers(src: dict) -> dict:
    """构造某发行源的请求头；GitHub 源按需注入只读令牌。

    令牌**每次请求时才读**，而不是模块导入时定死 —— 令牌文件是运维事后补写的，
    导入时读会永远拿到空值，必须重启服务才生效（实测踩过：写完文件仍显示限流）。
    """
    headers = {"User-Agent": "fnmusic-ext"}
    headers.update(src.get("headers") or {})
    if src.get("token"):
        tok = _github_token()
        if tok:
            headers["Authorization"] = f"Bearer {tok}"
    return headers


def _parse_version(raw: str) -> tuple:
    """把 'v2.6.16' / '2.6.3' / '2.6' 解析为 (major, minor, patch) 元组；失败返回 ()。

    仅做语义化版本的三段数字比较，不引入打包依赖。'2.6' 视作 (2,6,0)。
    """
    m = _VERSION_RE.match(str(raw or "").strip())
    if not m:
        return ()
    return (int(m.group(1)), int(m.group(2)), int(m.group(3)))


def _newer_than(remote: str, local: str) -> bool:
    """远端是否新于本地。任一版本号不可解析时保守返回 False（不打扰用户）。"""
    r, l = _parse_version(remote), _parse_version(local)
    if not r or not l:
        return False
    return r > l


def _changelog_notes(local: str, remote: str, limit: int = 12) -> list:
    """从本地 CHANGELOG.md 抽取 (local, remote] 之间的升级点条目。

    CHANGELOG 格式为 '## [2.6.3] - 2026-09-30' + '### 修复/变更/新增' + 列表项。
    只取严格高于本机版本的段落，按版本从新到旧倒序，每个版本最多 limit 条。
    解析失败一律返回空列表（前端据此隐藏升级点区块，不影响其他功能）。
    """
    try:
        text = CHANGELOG_PATH.read_text(encoding="utf-8")
    except OSError:
        return []

    local_v = _parse_version(local)
    remote_v = _parse_version(remote)
    if not local_v:
        return []

    # 按 '## [x.y.z] - date' 切段
    chunks = re.split(r"^##\s+\[([^\]]+)\]\s*-\s*(.+)$", text, flags=re.M)
    # chunks[0] 是文件头，之后每两个元素一组：版本号、日期、段落正文…
    out: list = []
    for i in range(1, len(chunks) - 2, 3):
        ver_raw, _date, body = chunks[i], chunks[i + 1], chunks[i + 2]
        if ver_raw.strip().lower() == "unreleased":
            continue
        v = _parse_version(ver_raw)
        if not v:
            continue
        if v <= local_v:
            continue
        if remote_v and v > remote_v:
            continue
        # 取该版本段落下所有 '- ' 列表项（升级点）
        items = []
        for line in body.splitlines():
            s = line.strip()
            if not s.startswith("- "):
                continue
            title = re.sub(r"\*\*(.+?)\*\*.*", r"\1", s[2:]).strip()
            title = re.sub(r"\s+", " ", title)
            if title:
                items.append({"text": title[:160], "raw": s[2:][:400]})
        if items:
            out.append({
                "version": ver_raw.strip(),
                "date": _date.strip(),
                "items": items[:limit],
                "total": len(items),
            })
    out.sort(key=lambda x: _parse_version(x["version"]) or (0,), reverse=True)
    return out


def _normalize_release(data: dict, src: dict) -> "dict | None":
    """把一条 release JSON 归一成内部结构；无版本号返回 None。"""
    tag = str(data.get("tag_name") or data.get("name") or "").strip()
    if not tag:
        return None
    return {
        "version": tag.lstrip("vV"),
        "tag": tag,
        "name": str(data.get("name") or tag),
        "notes": str(data.get("body") or "")[:20000],
        "url": str(data.get("html_url") or "") or src["page"],
        "page": src["page"],
        "published": str(data.get("published_at") or data.get("created_at") or ""),
        "assets": [
            {
                "name": str(a.get("name") or ""),
                "size": a.get("size") or 0,
                "url": str(a.get("browser_download_url") or ""),
            }
            for a in (data.get("assets") or [])
            if isinstance(a, dict) and str(a.get("name") or "").endswith(".fpk")
        ],
    }


async def _fetch_latest_release(request: Request) -> "tuple[dict | None, str]":
    """依次尝试各发行源，返回 (release_dict, 来源名)；全失败返回 (None, "")。

    策略：先打 releases/latest（快、权威），再用 releases 列表交叉校验 —— 若列表里
    存在版本号更大的正式版（latest 标记陈旧 / 预发布被排除等），以更大的那条为准。
    这样既省一次请求，又不会因 latest 标记不规范而漏报新版本。
    草稿（draft）与预发布（prerelease）一律排除。
    单源超时 6 秒即换下一个源，避免管理台被慢源拖住。

    踩坑（务必保留这里的"不提前 return"）：**不能拿到第一个能用的源就返回**。
    GitHub 未认证 API 只有 60 次/小时/IP，很容易撞 403；而 Gitee 镜像常常没同步
    新版本（实测停在 v2.6.16，资产还是 zip/tar）。早先"GitHub 失败就转 Gitee
    并直接返回"，于是 GitHub 一限流就把「远端最新 2.6.17」降级成「Gitee 的 2.6.16」，
    再拿 2.6.16 和本地 2.6.16 一比 —— 得到 has_update=false，
    **有新版却提示"已是最新"**，错误被完美掩盖成正常。
    现在改为遍历所有源取版本号最大者；只有全部源都失败才算检测失败。
    """
    client = get_http(request)
    best_overall: "dict | None" = None
    best_src = ""
    for src in RELEASE_SOURCES:
        headers = _source_headers(src)
        # --- 1) latest 接口 ---
        best: "dict | None" = None
        try:
            resp = await client.get(src["api"], headers=headers, timeout=6.0)
            if resp.status_code < 400:
                data = resp.json()
                if isinstance(data, dict) and not data.get("draft") and not data.get("prerelease"):
                    best = _normalize_release(data, src)
        except Exception as exc:  # noqa: BLE001
            logger.debug("release latest %s failed: %s", src["name"], exc)
        if best is None:
            continue
        # --- 2) 列表交叉校验，取版本号最大者 ---
        list_api = src.get("list_api")
        if list_api:
            try:
                resp = await client.get(list_api, headers=headers, timeout=6.0)
                if resp.status_code < 400:
                    items = resp.json()
                    if isinstance(items, list):
                        for it in items:
                            if not isinstance(it, dict):
                                continue
                            if it.get("draft") or it.get("prerelease"):
                                continue
                            cand = _normalize_release(it, src)
                            if cand and _newer_than(cand["version"], best["version"]):
                                best = cand
            except Exception as exc:  # noqa: BLE001 —— 列表失败不影响 latest 结果
                logger.debug("release list %s failed: %s", src["name"], exc)
        # 不提前返回：继续试下一个源，最后在所有源里取版本号最大的那条
        if best is not None and (best_overall is None
                                 or _newer_than(best["version"], best_overall["version"])):
            best_overall, best_src = best, src["name"]
    return best_overall, best_src


# 镜像可达性缓存：{源名: (是否可达, 时间戳)}，TTL 1 小时。
# 展示镜像前先探一次可达性，绝不把点不开的链接（如未开通的 Gitee 账号）呈现给用户。
_MIRROR_PROBE_TTL_S = 3600.0
_MIRROR_PROBE: "dict[str, tuple[bool, float]]" = {}


async def _probe_source_reachable(client: httpx.AsyncClient, src: dict) -> bool:
    """探测某发行源是否真实可用（仓库存在且能读到 release）。

    判据：latest 接口返回 2xx/3xx。404（Not Found Project）即视为不可用 ——
    这正是 Gitee 侧「账号/仓库不存在」的表现。探测失败一律记为不可达，不抛异常。
    """
    name = src.get("name") or ""
    hit = _MIRROR_PROBE.get(name)
    if hit and time.time() - hit[1] < _MIRROR_PROBE_TTL_S:
        return hit[0]
    headers = _source_headers(src)
    ok = False
    try:
        resp = await client.get(src["api"], headers=headers, timeout=5.0)
        ok = resp.status_code < 400
    except Exception as exc:  # noqa: BLE001
        logger.debug("mirror probe %s failed: %s", name, exc)
        ok = False
    if len(_MIRROR_PROBE) > 20:
        _MIRROR_PROBE.clear()
    _MIRROR_PROBE[name] = (ok, time.time())
    return ok


async def _available_mirrors(request: Request, working: str = "") -> list:
    """返回可点击的镜像列表（已过滤掉探测不可达的源）。

    working：本次实际取到数据的源，优先排在前；探测不可达的一律不展示，
    避免用户点到 404 死链。
    """
    client = get_http(request)
    out: list = []
    for src in RELEASE_SOURCES:
        if src["name"] == working or await _probe_source_reachable(client, src):
            out.append({"name": src["name"], "page": src["page"]})
    return out


# ------------------------------------------------------------------ API --

@app.get("/healthz")
async def healthz():
    return {"ok": True}


def _header_map(scope) -> dict[str, str]:
    out: dict[str, str] = {}
    for key, value in scope.get("headers") or []:
        out[key.decode("latin-1").lower()] = value.decode("latin-1")
    return out


def _is_admin(headers: dict[str, str]) -> bool:
    return headers.get("x-trim-isadmin", "").lower() == "true"


@app.get("/api/status")
async def api_status(request: Request):
    values = read_env()
    provider = current_provider(values)
    processes = supervisor_status()
    services: dict[str, dict] = {}
    for name, base in (("musicdl", CONF["musicdl_url"]), ("musicbox", CONF["musicbox_url"]),
                       ("lxmusic", CONF["lx_url"])):
        if name in PROVIDERS and name != provider:
            services[name] = {"reachable": False, "note": "未启用（按需未启动）"}
            continue
        ok, data = await _fetch_json(request, f"{base}/healthz")
        services[name] = {"reachable": ok, "detail": data if ok else data.get("error", "")}
    lx_source = None
    if provider == "lxmusic":
        ok, data = await _fetch_json(request, f"{CONF['lx_url']}/api/v1/source")
        lx_source = data.get("data") if ok else {"error": data.get("error", "unreachable")}
    return {
        "ok": True,
        "version": _read_version(),
        "deploy_mode": values.get("FNMUSIC_DEPLOY_MODE", "docker"),
        "current_provider": provider or "none",
        "processes": {name: processes.get(name, {"state": "UNKNOWN", "detail": ""})
                      for name in ("musicdl", "musicbox", "lxmusic", "webui")},
        "previews": {p: round(preview_seconds_left(p)) for p in list(_preview_until)},
        "services": services,
        "lx_source": lx_source,
    }


@app.get("/api/version")
async def api_version(request: Request):
    """版本检测与升级点查询（只提示不强制）。

    无论远端是否可达都返回 200：拉不到时 checked=False，前端显示「未检查到
    新版本」并保留手动重试按钮，绝不因版本检测失败影响其他功能。
    """
    local = _read_version()
    base = {
        "ok": True,
        "current": local,
        "releases_page": RELEASE_SOURCES[0]["page"],
        # 镜像列表在检测到具体来源后再补齐（见下方），此处先留空避免展示未探测的死链
        "mirrors": [],
    }
    try:
        rel, source = await _fetch_latest_release(request)
    except Exception as exc:  # noqa: BLE001 —— 永不因检测失败而报错
        logger.info("version check failed: %s", exc)
        return JSONResponse({**base, "checked": False, "has_update": False,
                             "error": "无法连接版本源（不影响使用）"})
    if rel is None:
        return JSONResponse({**base, "checked": False, "has_update": False,
                             "error": "无法连接版本源（不影响使用）"})

    remote = rel["version"]
    # 降级告警：主源（GitHub）未参与本次判定时必须如实说明，不能让用户以为
    # 「所有源都没有更新」。GitHub 匿名 API 只有 60 次/小时/IP，很容易 403；
    # 若同时 Gitee 镜像又落后，就会出现"明明有新版却显示已是最新"。
    notices: list[str] = []
    if source != RELEASE_SOURCES[0]["name"]:
        notices.append(f"主版本源 {RELEASE_SOURCES[0]['name']} 本次不可用（多为访问频率限制），"
                       f"当前结果来自镜像「{source}」，可能滞后于最新发行版")
    has_update = _newer_than(remote, local)
    # 镜像列表：只展示实测可达的源（探测失败/404 的不展示），避免用户点到死链
    mirrors = await _available_mirrors(request, working=source)
    return {
        **base,
        "mirrors": mirrors,
        "checked": True,
        "source": source,
        "notices": notices,
        "latest": remote,
        "latest_tag": rel["tag"],
        "latest_name": rel["name"],
        "has_update": has_update,
        "url": rel["url"],
        "notes": rel["notes"],
        "published": rel["published"],
        "assets": rel["assets"],
        "changelog": _changelog_notes(local, remote),
        # 能否提供离线完整包（只作提示用，真正的准入判断在 upgrade.start_upgrade 里）
        "can_install": bool(_pick_offline_asset(rel["assets"], remote)),
        "free_mb": _upgrade_free_mb(),
    }


def _pick_offline_asset(assets: list, version: str) -> "dict | None":
    """挑离线完整包。

    远端同时挂 `fnmusic-ext-<v>.fpk`（离线，约 405MB）和 `fnmusic-ext-<v>-online.fpk`
    （在线，约 5MB，装机时现拉 Docker 镜像）。带 -online 的一律排除：用户的 NAS
    未必能连上 Docker 仓库，选错就装不上。
    """
    for a in assets or []:
        name = str(a.get("name") or "")
        if re.search(r"-online\.fpk$", name, re.I):
            continue
        if name.endswith(".fpk") and str(version) in name:
            return a
    for a in assets or []:
        name = str(a.get("name") or "")
        if name.endswith(".fpk") and not re.search(r"-online\.fpk$", name, re.I):
            return a
    return None


def _upgrade_free_mb() -> int:
    try:
        return upgrade.disk_free_mb()
    except Exception:  # noqa: BLE001
        return -1


@app.get("/api/upgrade/state")
async def api_upgrade_state():
    """轮询安装包下载进度。状态落盘，页面刷新或服务重启后仍能查到真实结果。"""
    return {"ok": True, **(upgrade.read_state())}


class UpgradeBody(BaseModel):
    target: str = ""


@app.post("/api/upgrade/start")
async def api_upgrade_start(body: UpgradeBody, request: Request):
    """发起安装包下载：拉取官方 fpk → 校验 sha256 → 存到宿主可见目录。

    只做「可选动作」，任何失败都不影响当前版本继续使用。
    注意：fnOS 未提供可用的自动安装接口（appcenter-cli install-fpk 对已安装
    应用是空操作），所以这里**不装**，只把包准备好并指引用户手动安装。
    """
    local = _read_version()
    target = (body.target or "").strip().lstrip("vV")
    if not target:
        return JSONResponse({"ok": False, "error": "缺少目标版本"}, status_code=400)
    try:
        rel, _src = await _fetch_latest_release(request)
    except Exception as exc:  # noqa: BLE001
        return JSONResponse({"ok": False, "error": f"无法连接版本源：{exc}"}, status_code=503)
    if not rel:
        return JSONResponse({"ok": False, "error": "无法连接版本源"}, status_code=503)
    # 只允许升级到远端真实存在的那个版本，不接受调用方随意指定
    if target != rel["version"]:
        return JSONResponse(
            {"ok": False, "error": f"目标版本 v{target} 与远端最新 v{rel['version']} 不一致"},
            status_code=400,
        )
    try:
        result = await upgrade.start_upgrade(rel["assets"], target, local)
    except ValueError as exc:
        return JSONResponse({"ok": False, "error": str(exc)}, status_code=400)
    except Exception as exc:  # noqa: BLE001
        logger.exception("start upgrade failed")
        return JSONResponse({"ok": False, "error": str(exc)}, status_code=500)
    return result


@app.get("/api/config")
async def api_config():
    values = read_env()
    return {
        "ok": True,
        "values": {key: values.get(key, spec["default"]) for key, spec in SCHEMA.items()},
        "schema": SCHEMA,
        "env_path": str(ENV_PATH),
    }


class ConfigBody(BaseModel):
    values: dict


class PreviewBody(BaseModel):
    provider: str


@app.post("/api/preview")
async def api_preview(body: PreviewBody, request: Request):
    """点选未启用的音源卡片：临时拉起进程供预览（不写 .env，倒计时自动停止）。"""
    provider = body.provider
    if provider not in PROVIDERS:
        raise HTTPException(status_code=400, detail="provider 必须是 musicdl/musicbox/lxmusic 之一")
    if current_provider(read_env()) == provider:
        return {"ok": True, "preview": False, "note": "该音源已启用，进程常驻"}
    if preview_seconds_left(provider) > 0:
        preview_renew(provider)
        return {"ok": True, "preview": True, "seconds_left": preview_seconds_left(provider)}
    code, out = supervisorctl("start", PROVIDER_PROGRAM[provider])
    if code != 0:
        return JSONResponse(content={"ok": False, "error": out or "supervisorctl start 失败"}, status_code=500)
    client = get_http(request)
    for _ in range(60):  # 等待服务真正可用（healthz），最长约 30s
        try:
            r = await client.get(f"{PROVIDER_HEALTH[provider]}/healthz", timeout=2.0)
            if r.status_code == 200:
                break
        except httpx.HTTPError:
            pass
        await asyncio.sleep(0.5)
    _preview_until[provider] = time.monotonic() + PREVIEW_TTL
    return {"ok": True, "preview": True, "seconds_left": PREVIEW_TTL}


@app.put("/api/config")
async def api_config_put(body: ConfigBody, request: Request):
    before = read_env()
    try:
        updates = validate_updates(body.values)
    except ValueError as exc:
        return JSONResponse(content={"ok": False, "error": str(exc)}, status_code=400)

    # lx 换源前置校验：新 URL 必须先通过 lxmusic verify 才写入
    lx_url_changed = updates.get("LX_SOURCE_URL") not in (None, before.get("LX_SOURCE_URL", ""))
    after_preview = dict(before)
    after_preview.update(updates)
    if lx_url_changed and current_provider(after_preview) == "lxmusic":
        new_url = updates["LX_SOURCE_URL"]
        client = get_http(request)
        try:
            resp = await client.post(f"{CONF['lx_url']}/api/v1/source/verify",
                                     json={"url": new_url}, timeout=130.0)
            report = _resp_json(resp)
        except Exception as exc:  # noqa: BLE001
            report = {"ok": False, "data": {"message": str(exc)}}
        if not report.get("ok"):
            message = (report.get("data") or {}).get("message") or report.get("error") or "校验失败"
            return JSONResponse(
                content={"ok": False, "error": f"洛雪源校验未通过：{message}"}, status_code=400
            )
        platforms = (report.get("data") or {}).get("platforms") or []
        if platforms:
            updates.setdefault("LX_SOURCES", ",".join(platforms))

    old_provider = current_provider(before)
    changed = write_env(updates)
    if not changed:
        return {"ok": True, "changed": [], "actions": [], "note": "配置无变化"}

    after = read_env()
    new_provider = current_provider(after)
    actions: list[dict] = []

    # 音源切换（先停旧再起新）
    if old_provider != new_provider:
        actions.extend(switch_provider_process(old_provider, new_provider))
    # lx 换源激活：热切换 SOURCE_MANAGER（进程刚被拉起时 state.json 仍是旧源，必须显式激活）
    if new_provider == "lxmusic" and lx_url_changed:
        client = get_http(request)
        try:
            resp = await client.post(f"{CONF['lx_url']}/api/v1/source",
                                     json={"url": after["LX_SOURCE_URL"]}, timeout=130.0)
            payload = _resp_json(resp)
            ok = resp.status_code == 200 and payload.get("ok", False)
            err = "" if ok else (payload.get("error") or f"HTTP {resp.status_code}")
        except Exception as exc:  # noqa: BLE001
            ok, err = False, str(exc)
        actions.append({"kind": "lx_activate", "ok": ok, "error": err or ""})
    elif new_provider == "musicdl" and (
        "FNMUSIC_ONLINE_SOURCES" in changed or "MUSICDL_SOURCES" in changed
    ):
        code, out = supervisorctl("restart", "musicdl")
        actions.append({"kind": "process", "program": "musicdl", "op": "restart",
                        "ok": code == 0, "error": "" if code == 0 else out})

    # 预览收尾：保存启用的转正常驻，其余预览进程立即停止
    actions.extend(preview_reconcile_after_save())

    restart_keys = [k for k in changed if SCHEMA.get(k, {}).get("reload") == "restart"]
    return {"ok": True, "changed": changed, "actions": actions, "restart_keys": restart_keys}


@app.post("/api/lx/verify")
async def api_lx_verify(body: ConfigBody, request: Request):
    preview_renew("lxmusic")  # 预览期间测试源视为活跃，续期倒计时
    url = str((body.values or {}).get("url") or "").strip()
    if not url.lower().startswith(("http://", "https://", "file://")):
        raise HTTPException(status_code=400, detail="url 必须以 http:// 、https:// 或 file:// 开头")
    client = get_http(request)
    try:
        resp = await client.post(f"{CONF['lx_url']}/api/v1/source/verify",
                                 json={"url": url}, timeout=130.0)
        return JSONResponse(content=_resp_json(resp) or {"ok": False},
                            status_code=resp.status_code)
    except httpx.HTTPError as exc:
        raise HTTPException(status_code=502, detail=f"lxmusic 服务不可达: {exc}") from exc


# 大模型连接测试：探测用固定 20s，允许跟随 .env 里的 FNMUSIC_LLM_TIMEOUT_S（5~60s，与
# proxy/recommend.py 的 llm_timeout_s 同一口径），但绝不因测试而无限等。
_LLM_TEST_TIMEOUT_S = 20.0

# 上游 4xx/5xx 各状态的常见成因，直接给用户看，省得对着英文报错猜
_LLM_STATUS_HINTS = {
    400: "请求被拒绝：模型名可能不存在，或该模型不接受 messages 格式",
    401: "鉴权失败：API Key 无效或已过期",
    403: "无权限：Key 有效但无权访问该模型（常见于未开通或欠费）",
    404: "接口不存在：Base URL 只填到 /v1 一级，/chat/completions 由程序自动补",
    408: "网关超时",
    413: "请求体过大",
    422: "参数不被接受：多为模型名写错",
    429: "限流或额度耗尽",
    500: "服务端内部错误",
    502: "网关错误：Base URL 可能指向了异常的反代后端",
    503: "服务暂不可用",
    504: "网关超时",
}


def _llm_test_timeout_s() -> float:
    try:
        raw = float(read_env().get("FNMUSIC_LLM_TIMEOUT_S", "") or _LLM_TEST_TIMEOUT_S)
    except ValueError:
        raw = _LLM_TEST_TIMEOUT_S
    return min(60.0, max(5.0, raw))


def _redact(text: str, secret: str) -> str:
    """上游报错里可能回显 Authorization 的值，回显即泄漏，出网关前必须抹掉。"""
    out = text or ""
    if secret:
        out = out.replace(secret, "***")
        if len(secret) > 8:  # 部分中转只回显前缀
            out = out.replace(secret[:8], "***")
    return out[:400]


@app.post("/api/llm/test")
async def api_llm_test(body: ConfigBody, request: Request):
    """用输入框当前值实测一次 /chat/completions（不写 .env），判断大模型配置是否正确。

    字段留空则回落到已保存的 .env 值，便于「保存后想复验」和「只改一项试其他项」。
    URL 拼接与鉴权方式同 proxy/recommend.py 的 call_llm()，保证测试通过即真实可用。
    """
    values = body.values or {}
    saved = read_env()
    base = (str(values.get("base_url") or "").strip().rstrip("/")
            or saved.get("FNMUSIC_LLM_BASE_URL", "").strip().rstrip("/"))
    key = (str(values.get("api_key") or "").strip()
           or saved.get("FNMUSIC_LLM_API_KEY", "").strip())
    model = (str(values.get("model") or "").strip()
             or saved.get("FNMUSIC_LLM_MODEL", "").strip() or "gpt-4o-mini")
    if not base:
        raise HTTPException(status_code=400, detail="请先填写 Base URL")
    if not base.lower().startswith(("http://", "https://")):
        raise HTTPException(status_code=400, detail="Base URL 必须以 http:// 或 https:// 开头")
    if not key:
        raise HTTPException(status_code=400, detail="请先填写 API Key")
    url = base if base.endswith("/chat/completions") else f"{base}/chat/completions"
    timeout = _llm_test_timeout_s()
    started = time.monotonic()

    def elapsed_ms() -> int:
        return int((time.monotonic() - started) * 1000)

    client = get_http(request)
    try:
        resp = await client.post(
            url,
            json={
                "model": model,
                "temperature": 0,
                "max_tokens": 1,  # 只验连通与鉴权，不烧用户额度
                "messages": [{"role": "user", "content": "ping"}],
            },
            headers={"Authorization": f"Bearer {key}", "Content-Type": "application/json"},
            timeout=timeout,
        )
    except httpx.TimeoutException:
        return {"ok": False, "stage": "connect", "url": url, "model": model,
                "timeout_s": timeout, "elapsed_ms": elapsed_ms(),
                "message": f"连接超时：{timeout:.0f}s 内没有响应"}
    except httpx.HTTPError as exc:
        return {"ok": False, "stage": "connect", "url": url, "model": model,
                "timeout_s": timeout, "elapsed_ms": elapsed_ms(),
                "message": _redact(f"无法连接（{type(exc).__name__}）：{exc}", key)}

    status = resp.status_code
    detail = ""
    reply = ""
    model_echo = ""
    try:
        payload = resp.json()
    except Exception:  # noqa: BLE001 —— 非 JSON 响应体按纯文本处理
        payload = None
    if isinstance(payload, dict):
        model_echo = str(payload.get("model") or "")
        err = payload.get("error")
        if isinstance(err, dict):
            detail = str(err.get("message") or err.get("code") or "")
        elif isinstance(err, str):
            detail = err
        if not detail:
            choices = payload.get("choices") or []
            if choices and isinstance(choices[0], dict):
                reply = str((choices[0].get("message") or {}).get("content") or "")[:120]
    if not detail:
        detail = (resp.text or "").strip()
    return {
        "ok": status < 400,
        "stage": "response",
        "url": url,
        "model": model,
        "model_echo": model_echo,
        "status": status,
        "elapsed_ms": elapsed_ms(),
        "reply": _redact(reply, key),
        "message": _redact(detail, key),
        "hint": _LLM_STATUS_HINTS.get(status, "" if status < 400 else f"HTTP {status}"),
    }


def _lx_script_limits(filename: str, script: str) -> None:
    if not (filename or "").strip().lower().endswith(".js"):
        raise HTTPException(status_code=400, detail="只支持 .js 后缀的洛雪源脚本文件")
    if len(script.encode("utf-8")) > 9_000_000:
        raise HTTPException(status_code=400, detail="脚本超过 9MB 大小上限")


@app.post("/api/lx/upload")
async def api_lx_upload(request: Request):
    """上传 .js：管理页/NAS 选择发 JSON {filename, script}，也接受 multipart 文件。

    校验后转给 lxmusic 落盘，返回 file:// URL。
    """
    preview_renew("lxmusic")
    content_type = (request.headers.get("content-type") or "").lower()
    if "application/json" in content_type:
        try:
            payload = await request.json()
        except Exception as exc:  # noqa: BLE001
            raise HTTPException(status_code=400, detail="请求体必须是 JSON") from exc
        if not isinstance(payload, dict):
            raise HTTPException(status_code=400, detail="请求体必须是 JSON 对象")
        filename = str(payload.get("filename") or "")
        script = payload.get("script")
        if not isinstance(script, str) or not script:
            raise HTTPException(status_code=400, detail="缺少 script")
    elif "multipart/form-data" in content_type:
        form = await request.form()
        upload = form.get("file")
        if upload is None or not hasattr(upload, "filename"):
            raise HTTPException(status_code=400, detail="缺少 file 字段")
        filename = upload.filename or ""
        raw = await upload.read()
        if len(raw) > 9_000_000:
            raise HTTPException(status_code=400, detail="脚本超过 9MB 大小上限")
        try:
            script = raw.decode("utf-8")
        except UnicodeDecodeError as exc:
            raise HTTPException(status_code=400, detail="脚本不是有效的 UTF-8 文本") from exc
    else:
        raise HTTPException(
            status_code=400, detail="请用 application/json 或 multipart/form-data 上传文件")
    _lx_script_limits(filename, script)
    client = get_http(request)
    try:
        resp = await client.post(f"{CONF['lx_url']}/api/v1/source/upload",
                                 json={"filename": filename, "script": script},
                                 timeout=30.0)
        return JSONResponse(content=_resp_json(resp) or {"ok": False},
                            status_code=resp.status_code)
    except httpx.HTTPError as exc:
        raise HTTPException(status_code=502, detail=f"lxmusic 服务不可达: {exc}") from exc


@app.get("/api/platforms")
async def api_platforms(request: Request):
    preview_renew("musicdl")  # 预览期间查看平台列表视为活跃，续期倒计时
    ok, data = await _fetch_json(request, f"{CONF['musicdl_url']}/sources")
    if not ok:
        return JSONResponse(
            content={"ok": False, "error": data.get("error", "musicdl 服务不可达"),
                     "hint": "musicdl 进程未启用时无法获取平台列表"},
            status_code=503,
        )
    return {"ok": True, "enabled": data.get("enabled") or [], "registered": data.get("registered") or []}


# ------------------------------------------------- 网易扫码（反代 musicbox） --

@app.api_route("/api/netease/auth/{path:path}", methods=["GET", "POST"])
async def netease_auth_proxy(path: str, request: Request):
    """透传 musicbox 的 auth 接口（登录/轮询/状态），路径段白名单内。"""
    if path not in ("login", "login/check", "status"):
        raise HTTPException(status_code=404, detail="unknown auth endpoint")
    preview_renew("musicbox")  # 预览期间扫码/查状态视为活跃，续期倒计时
    target = f"{CONF['musicbox_url']}/api/v1/auth/{path}"
    client = get_http(request)
    try:
        resp = await client.request(
            request.method, target,
            params=dict(request.query_params),
            json=(await request.json()) if request.method == "POST" and await request.body() else None,
            timeout=30.0,
        )
    except httpx.HTTPError as exc:
        raise HTTPException(status_code=502, detail=f"musicbox 服务不可达: {exc}") from exc
    return Response(content=resp.content, status_code=resp.status_code,
                    media_type=resp.headers.get("content-type", "application/json"))


@app.get("/api/netease/qr")
async def netease_qr(unikey: str = Query(...)):
    """把登录链接渲染为 SVG 二维码（无 PIL 依赖，前端直接 <img> 展示）。"""
    if not unikey.strip():
        raise HTTPException(status_code=400, detail="unikey cannot be empty")
    try:
        import qrcode
        import qrcode.image.svg
    except ImportError as exc:
        raise HTTPException(status_code=501, detail="qrcode not installed") from exc
    url = f"https://music.163.com/login?codekey={unikey.strip()}"
    img = qrcode.make(url, image_factory=qrcode.image.svg.SvgPathImage, box_size=12)
    buf = io.BytesIO()
    img.save(buf)
    return Response(content=buf.getvalue(), media_type="image/svg+xml")


# ------------------------------------------------------------------ 静态前端 --

class NoCacheStatic(StaticFiles):
    """静态资源强制不缓存。

    踩坑：StaticFiles 默认只发 ETag + Last-Modified，没有 Cache-Control。
    浏览器于是对 app.js / style.css / index.html 做启发式缓存（典型 10% 剩余时间），
    而飞牛桌面是常驻 iframe，会一直复用首次加载的那份旧脚本 —— 结果就是
    「移动端能看到升级提示（每次新开页面，重新校验），
      桌面端死活没有（一直吃缓存里的旧 app.js，里面根本没有渲染角标的逻辑）」。
    这里显式 no-store，让每次进页面都拿当前版本，前端更新立刻生效。
    版本检测/升级这类"提示型"功能最怕的就是提示被缓存吞掉。
    """

    def file_response(self, *args, **kwargs):  # noqa: ANN002, ANN003
        resp = super().file_response(*args, **kwargs)
        resp.headers["Cache-Control"] = "no-store, no-cache, must-revalidate, max-age=0"
        resp.headers["Pragma"] = "no-cache"
        return resp


@app.get("/")
async def index():
    resp = FileResponse(STATIC_DIR / "index.html")
    resp.headers["Cache-Control"] = "no-store, no-cache, must-revalidate, max-age=0"
    resp.headers["Pragma"] = "no-cache"
    return resp


@app.head("/")
async def index_head():
    """HEAD 也要支持：浏览器/代理发条件请求（If-None-Match）时用的是 HEAD，
    只注册 GET 会返回 405，反而让"禁缓存"这条链路在某些客户端上失效。"""
    return Response(status_code=200, headers={
        "Cache-Control": "no-store, no-cache, must-revalidate, max-age=0",
        "Pragma": "no-cache",
    })


app.mount("/static", NoCacheStatic(directory=str(STATIC_DIR)), name="static")

# 飞牛桌面 iframe 不能嵌 http://主机:8774（桌面是 HTTPS，混合内容会被浏览器丢掉，窗口一片空白）。
# 入口改走网关同源路径 /app/fnmusic-ext，这里把该前缀剥掉，直连 :8774 的 /api 不受影响。
DESKTOP_PREFIX = "/app/fnmusic-ext"


class DesktopPrefixMiddleware:
    def __init__(self, app, prefix: str = DESKTOP_PREFIX):
        self.app = app
        self.prefix = prefix

    async def __call__(self, scope, receive, send):
        if scope["type"] in ("http", "websocket"):
            path = scope.get("path") or ""
            if path == self.prefix or path.startswith(self.prefix + "/"):
                scope = dict(scope)
                stripped = path[len(self.prefix):] or "/"
                scope["path"] = stripped
                if isinstance(scope.get("raw_path"), (bytes, bytearray)):
                    scope["raw_path"] = stripped.encode("ascii")
        await self.app(scope, receive, send)


class AuthMiddleware:
    """管理接口要求飞牛网关注入的管理员身份。桌面前缀由外层中间件先剥掉。"""

    def __init__(self, app):
        self.app = app

    async def __call__(self, scope, receive, send):
        if scope["type"] != "http":
            await self.app(scope, receive, send)
            return
        path = scope.get("path") or ""
        if not path.startswith("/api/") or _is_admin(_header_map(scope)):
            await self.app(scope, receive, send)
            return
        body = '{"ok":false,"error":"需要管理员"}'.encode()
        await send({
            "type": "http.response.start",
            "status": 403,
            "headers": [
                [b"content-type", b"application/json; charset=utf-8"],
                [b"content-length", str(len(body)).encode()],
            ],
        })
        await send({"type": "http.response.body", "body": body})


app.add_middleware(AuthMiddleware)
app.add_middleware(DesktopPrefixMiddleware)
